// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Example
{
    using TechTalk.SpecFlow;
    using Autofac;
    using Autofac.Configuration;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("ExampleFeature")]
    public partial class ExampleFeatureFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private OpenQA.Selenium.IWebDriver driver;
        
        private IContainer container;
        
        private string _googletranslate;
        
#line 1 "ExampleFeature.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUp()]
        public virtual void FeatureSetup()
        {
            var builder = new ContainerBuilder();
            builder.RegisterModule(new ConfigurationSettingsReader());
            this.container = builder.Build();
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(null, 0);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "ExampleFeature", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDown()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
            try {((Unickq.SeleniumHelper.WebDriverGrid.ICustomRemoteWebDriver) this.driver).UpdateTestResult();} catch (System.Exception) {}
            try {System.Threading.Thread.Sleep(50); this.driver.Quit(); } catch (System.Exception) {}
            this.driver = null;
            ScenarioContext.Current.Remove("Driver");
            ScenarioContext.Current.Remove("Container");
              System.Console.WriteLine(NUnit.Framework.TestContext.CurrentContext.Result.Outcome.Status.ToString());
            ScenarioContext.Current.Remove("GoogleTranslate");
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
            if(this.driver != null)
                ScenarioContext.Current.Add("Driver", this.driver);
            if(this.container != null)
                ScenarioContext.Current.Add("Container", this.container);
            if(this._googletranslate != null)
                ScenarioContext.Current.Add("GoogleTranslate", this._googletranslate);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void CheckWebsiteTitle(string uRL, string @string, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Browser:Chrome_local",
                    "Browser:BrowserStack_Win10_Chrome",
                    "Browser:TestingBot_ElCapitan_Safari",
                    "Browser:SauceLabs_Win7_Firefox",
                    "GoogleTranslate:FR",
                    "GoogleTranslate:DE",
                    "GoogleTranslate:UK"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Check website title", @__tags);
#line 10
this.ScenarioSetup(scenarioInfo);
#line 11
 testRunner.Given(string.Format("I have opened {0}", uRL), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 12
 testRunner.Then(string.Format("the title should contain \'{0}\'", @string), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Check website title: https://translate.google.com/")]
        [NUnit.Framework.TestCaseAttribute("Chrome_local", "FR", Category="Chrome_local,FR", TestName="CheckWebsiteTitle_HttpsTranslate_Google_Com with Chrome_local,FR")]
        [NUnit.Framework.TestCaseAttribute("Chrome_local", "DE", Category="Chrome_local,DE", TestName="CheckWebsiteTitle_HttpsTranslate_Google_Com with Chrome_local,DE")]
        [NUnit.Framework.TestCaseAttribute("Chrome_local", "UK", Category="Chrome_local,UK", TestName="CheckWebsiteTitle_HttpsTranslate_Google_Com with Chrome_local,UK")]
        [NUnit.Framework.TestCaseAttribute("BrowserStack_Win10_Chrome", "FR", Category="BrowserStack_Win10_Chrome,FR", TestName="CheckWebsiteTitle_HttpsTranslate_Google_Com with BrowserStack_Win10_Chrome,FR")]
        [NUnit.Framework.TestCaseAttribute("BrowserStack_Win10_Chrome", "DE", Category="BrowserStack_Win10_Chrome,DE", TestName="CheckWebsiteTitle_HttpsTranslate_Google_Com with BrowserStack_Win10_Chrome,DE")]
        [NUnit.Framework.TestCaseAttribute("BrowserStack_Win10_Chrome", "UK", Category="BrowserStack_Win10_Chrome,UK", TestName="CheckWebsiteTitle_HttpsTranslate_Google_Com with BrowserStack_Win10_Chrome,UK")]
        [NUnit.Framework.TestCaseAttribute("TestingBot_ElCapitan_Safari", "FR", Category="TestingBot_ElCapitan_Safari,FR", TestName="CheckWebsiteTitle_HttpsTranslate_Google_Com with TestingBot_ElCapitan_Safari,FR")]
        [NUnit.Framework.TestCaseAttribute("TestingBot_ElCapitan_Safari", "DE", Category="TestingBot_ElCapitan_Safari,DE", TestName="CheckWebsiteTitle_HttpsTranslate_Google_Com with TestingBot_ElCapitan_Safari,DE")]
        [NUnit.Framework.TestCaseAttribute("TestingBot_ElCapitan_Safari", "UK", Category="TestingBot_ElCapitan_Safari,UK", TestName="CheckWebsiteTitle_HttpsTranslate_Google_Com with TestingBot_ElCapitan_Safari,UK")]
        [NUnit.Framework.TestCaseAttribute("SauceLabs_Win7_Firefox", "FR", Category="SauceLabs_Win7_Firefox,FR", TestName="CheckWebsiteTitle_HttpsTranslate_Google_Com with SauceLabs_Win7_Firefox,FR")]
        [NUnit.Framework.TestCaseAttribute("SauceLabs_Win7_Firefox", "DE", Category="SauceLabs_Win7_Firefox,DE", TestName="CheckWebsiteTitle_HttpsTranslate_Google_Com with SauceLabs_Win7_Firefox,DE")]
        [NUnit.Framework.TestCaseAttribute("SauceLabs_Win7_Firefox", "UK", Category="SauceLabs_Win7_Firefox,UK", TestName="CheckWebsiteTitle_HttpsTranslate_Google_Com with SauceLabs_Win7_Firefox,UK")]
        public virtual void CheckWebsiteTitle_HttpsTranslate_Google_Com(string browser, string googletranslate)
        {
InitializeSeleniumBrowserGoogleTranslate(browser,googletranslate);
            this.CheckWebsiteTitle("https://translate.google.com/", "Google", ((string[])(null)));
#line hidden
        }
        
        private void InitializeSeleniumBrowserGoogleTranslate(string browser, string googletranslate)
        {
            this.driver = this.container.ResolveNamed<OpenQA.Selenium.IWebDriver>(browser);
            this._googletranslate = googletranslate;
        }
    }
}
#pragma warning restore
#endregion
