// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.2.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Example.Features
{
    using TechTalk.SpecFlow;
    using Autofac;
    using Autofac.Configuration;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("ExampleFeature2")]
    [NUnit.Framework.ParallelizableAttribute()]
    public partial class ExampleFeature2Feature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private OpenQA.Selenium.IWebDriver driver;
        
        private IContainer container;
        
        private string _googletranslate;
        
        [NUnit.Framework.OneTimeSetUp()]
        public virtual void FeatureSetup()
        {
            var builder = new ContainerBuilder();
            builder.RegisterModule(new ConfigurationSettingsReader());
            this.container = builder.Build();
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "ExampleFeature2", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDown()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            try {((Unickq.SeleniumHelper.WebDriverGrid.ICustomRemoteWebDriver) this.driver).UpdateTestResult();} catch (System.Exception) {}
            try {System.Threading.Thread.Sleep(50); this.driver.Quit(); } catch (System.Exception) {}
            driver = null;
            testRunner.ScenarioContext.Remove("Driver");
            testRunner.ScenarioContext.Remove("Container");
            testRunner.ScenarioContext.Remove("GoogleTranslate");
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
            if(this.driver != null)
              testRunner.ScenarioContext.Add("Driver", this.driver);
            if(this.container != null)
              testRunner.ScenarioContext.Add("Container", this.container);
            if(this._googletranslate != null)
              testRunner.ScenarioContext.Add("GoogleTranslate", this._googletranslate);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Check website title")]
        [NUnit.Framework.TestCaseAttribute("Chrome_local", "FR", "https://translate.google.com/", "Google", null, Category="Chrome_local,FR", TestName="CheckWebsiteTitle with Chrome_local,FR and \"https://translate.google.com/\" ,\"Goog" +
            "le\"")]
        [NUnit.Framework.TestCaseAttribute("Chrome_local", "DE", "https://translate.google.com/", "Google", null, Category="Chrome_local,DE", TestName="CheckWebsiteTitle with Chrome_local,DE and \"https://translate.google.com/\" ,\"Goog" +
            "le\"")]
        [NUnit.Framework.TestCaseAttribute("Firefox_local", "FR", "https://translate.google.com/", "Google", null, Category="Firefox_local,FR", TestName="CheckWebsiteTitle with Firefox_local,FR and \"https://translate.google.com/\" ,\"Goo" +
            "gle\"")]
        [NUnit.Framework.TestCaseAttribute("Firefox_local", "DE", "https://translate.google.com/", "Google", null, Category="Firefox_local,DE", TestName="CheckWebsiteTitle with Firefox_local,DE and \"https://translate.google.com/\" ,\"Goo" +
            "gle\"")]
        public virtual void CheckWebsiteTitle(string browser, string googletranslate, string uRL, string @string, string[] exampleTags)
        {
InitializeSeleniumBrowserGoogleTranslate(browser,googletranslate);
            string[] @__tags = new string[] {
                    "Browser:Chrome_local",
                    "Browser:Firefox_local",
                    "GoogleTranslate:FR",
                    "GoogleTranslate:DE"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Check website title", @__tags);
            this.ScenarioSetup(scenarioInfo);
            testRunner.Given(string.Format("I have opened {0}", uRL), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
            testRunner.Then(string.Format("the title should contain \'{0}\'", @string), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
            this.ScenarioCleanup();
        }
        
        private void InitializeSeleniumBrowserGoogleTranslate(string browser, string googletranslate)
        {
            this.driver = this.container.ResolveNamed<OpenQA.Selenium.IWebDriver>(browser);
            this._googletranslate = googletranslate;
        }
    }
}
#pragma warning restore
#endregion
